import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — LeadsSnap",
  description: "How LeadsSnap collects, processes, and protects your data.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen">
      <div className="max-w-2xl mx-auto px-4 py-8">
        <Link href="/" className="text-sm text-muted hover:text-foreground transition-colors">
          &larr; Back to home
        </Link>

        <h1 className="text-2xl font-bold mt-6 mb-2">Privacy Policy</h1>
        <p className="text-sm text-muted mb-8">Effective date: April 2026</p>

        <div className="space-y-8">
          <section>
            <h2 className="text-lg font-semibold mb-3">1. Introduction</h2>
            <p className="text-sm text-muted leading-relaxed">
              LeadsSnap is operated by Outpace CX. We are committed to protecting
              your privacy and handling your personal data responsibly. This Privacy
              Policy explains what data we collect, why we collect it, how we process
              it, and your rights under the General Data Protection Regulation (GDPR)
              and other applicable data protection laws.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">2. Data We Collect</h2>
            <p className="text-sm text-muted leading-relaxed mb-3">
              We collect the following categories of personal data:
            </p>
            <ul className="text-sm text-muted leading-relaxed list-disc pl-5 space-y-2">
              <li><strong className="text-foreground">Account information:</strong> Your email address and authentication provider (Google OAuth or magic link).</li>
              <li><strong className="text-foreground">Scanned contact data:</strong> Names, job titles, companies, email addresses, phone numbers, LinkedIn profiles, websites, and other contact details extracted from business cards, event badges, and QR codes.</li>
              <li><strong className="text-foreground">Card images:</strong> Photos of business cards and badges you upload for scanning.</li>
              <li><strong className="text-foreground">User profile (My Card):</strong> Your name, title, company, contact details, and profile photo that you voluntarily provide to create your digital business card.</li>
              <li><strong className="text-foreground">Ideal Customer Profile (ICP):</strong> Target job titles, industries, company sizes, and locations you define for lead scoring.</li>
              <li><strong className="text-foreground">AI-enriched data:</strong> Company intel, lead scores, and supplementary information generated by AI based on scanned data.</li>
              <li><strong className="text-foreground">Usage data:</strong> Events you create, export activity, and general app usage patterns.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">3. Why We Collect Data</h2>
            <p className="text-sm text-muted leading-relaxed mb-3">
              We process your data for the following purposes:
            </p>
            <ul className="text-sm text-muted leading-relaxed list-disc pl-5 space-y-2">
              <li>To provide the LeadsSnap service: scanning, storing, organizing, and exporting your leads.</li>
              <li>To use AI to extract contact information from card and badge images.</li>
              <li>To enrich leads with company intelligence and generate lead scores.</li>
              <li>To generate follow-up email drafts and other AI-assisted features.</li>
              <li>To authenticate your account and maintain session security.</li>
              <li>To improve and maintain the service.</li>
            </ul>
            <p className="text-sm text-muted leading-relaxed mt-3">
              The legal basis for processing is your consent (by using the service) and
              our legitimate interest in providing and improving LeadsSnap.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">4. Data Processors</h2>
            <p className="text-sm text-muted leading-relaxed mb-3">
              We use the following third-party processors to deliver the service:
            </p>
            <ul className="text-sm text-muted leading-relaxed list-disc pl-5 space-y-2">
              <li><strong className="text-foreground">Anthropic (Claude API):</strong> AI processing for card scanning, data enrichment, lead scoring, and email drafts. Card images and extracted text are sent to Anthropic for processing.</li>
              <li><strong className="text-foreground">Supabase:</strong> Database, user authentication, and file storage.</li>
              <li><strong className="text-foreground">Vercel:</strong> Application hosting and serverless functions.</li>
              <li><strong className="text-foreground">Google:</strong> OAuth authentication and Google Sheets API integration for lead export.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">5. Data Retention</h2>
            <p className="text-sm text-muted leading-relaxed">
              Your data is retained for as long as your account is active. You can
              delete individual leads at any time, and all associated data (including
              card images) will be permanently removed. If you delete your account, all
              your data is permanently deleted from our systems. We do not retain data
              after account deletion except where required by law.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">6. Your Rights Under GDPR</h2>
            <p className="text-sm text-muted leading-relaxed mb-3">
              If you are located in the European Economic Area (EEA), United Kingdom,
              or another jurisdiction with similar data protection laws, you have the
              following rights:
            </p>
            <ul className="text-sm text-muted leading-relaxed list-disc pl-5 space-y-2">
              <li><strong className="text-foreground">Right of access:</strong> Request a copy of all personal data we hold about you.</li>
              <li><strong className="text-foreground">Right to rectification:</strong> Ask us to correct inaccurate data.</li>
              <li><strong className="text-foreground">Right to erasure:</strong> Request deletion of your personal data.</li>
              <li><strong className="text-foreground">Right to data portability:</strong> Receive your data in a structured, machine-readable format (JSON).</li>
              <li><strong className="text-foreground">Right to restrict processing:</strong> Ask us to limit how we use your data.</li>
              <li><strong className="text-foreground">Right to object:</strong> Object to processing of your data for certain purposes.</li>
            </ul>
            <p className="text-sm text-muted leading-relaxed mt-3">
              You can exercise these rights using the in-app Account Settings page
              (export your data or delete your account) or by contacting us at{" "}
              <a href="mailto:support@leadssnap.com" className="text-accent hover:underline">support@leadssnap.com</a>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">7. Cookies</h2>
            <p className="text-sm text-muted leading-relaxed">
              LeadsSnap uses only essential session cookies provided by Supabase Auth
              to maintain your authenticated session. We do not use advertising
              cookies, analytics cookies, or any third-party tracking cookies.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">8. Data Security</h2>
            <p className="text-sm text-muted leading-relaxed">
              We implement appropriate technical and organizational measures to protect
              your data, including encrypted connections (HTTPS/TLS), secure
              authentication, and access controls.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">9. Changes to This Policy</h2>
            <p className="text-sm text-muted leading-relaxed">
              We may update this Privacy Policy from time to time. If we make material
              changes, we will notify you by email or through a notice in the app.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">10. Contact Us</h2>
            <p className="text-sm text-muted leading-relaxed">
              If you have any questions about this Privacy Policy or wish to exercise your data rights, contact us at:
            </p>
            <p className="text-sm text-muted leading-relaxed mt-2">
              <strong className="text-foreground">Outpace CX</strong><br />
              Email: <a href="mailto:support@leadssnap.com" className="text-accent hover:underline">support@leadssnap.com</a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-border text-sm text-muted">
          <Link href="/terms" className="text-accent hover:underline">Terms of Service</Link>
        </div>
      </div>
    </div>
  );
}
